# Generated by Django 4.2.5 on 2023-10-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_category_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='reminder',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
